### ISSUE TITLE
Server http://localize.im/ is down now =(

### ISSUE THREAD

**Issue by boris-dev** [delight-im/Localize#19]
Sorry It's not a bug in library, but I started to localize my project with this site and now work is almost done but today this site is not avalible. I dont know what to do.

**Comment by mwaclawek** [comment]
Thanks for reporting!

Can you please check again? For us, it's redirecting to HTTPS and working fine.

**Comment by boris-dev** [comment]
Thank you! You saved my life. Acctualy your site is amazing It saves many hours for my projects. I have 2 ideas how to improve this site to be perfect (accualy It's already perfect) :
1) add context for strings, just one field with comment about a string.
2) max length for string, sometimes(offen in my case)  you really need that translation cannot be more than some number of simbols.

**Comment by mwaclawek** [comment]
Thanks!

So the site is up again for you as well? Unfortunately, we have no idea what caused the outage nor when the site went up again.

Whenever that happens again, feel free to inform us via email. Apart from this solution, you can self-host the project, of course. But this shouldn't be necessary. The site should not go down that often, hopefully.

Regarding (1), that sounds like an important addition. Maybe you can add this as a separate issue? With (2), we're not that sure yet, but you may add an issue for this as well.

**Comment by boris-dev** [comment]
Alright, I will create 2 more issues. Thank you again, you made great project. I'm so glad that I found it.
