### ISSUE TITLE
sign up

### ISSUE THREAD

**Issue by ahsim** [delight-im/Localize#26]
how to sign up on www.localize.im?

**Comment by ocram** [comment]
You can’t sign up anymore, sorry!

As explained on its home page, the hosted instance available at `localize.im` is shutting down. So that’s why sign ups have been disabled.

You may host an instance yourself using the source code from this repository, or look for an alternative provider.

**Comment by xavimc** [comment]
Hello, 
I think you did a great job and very useful for some expensive translations. It's sad that is not maintained but thank you for the efforts.
As you suggested to Ahsim I'm trying to implement and host an instance of this project for my app.
I'm not an expert (I have no idea :) in fact ) in web development.... I managed to set the environment and the project, but when you try to create an account the link points to "pages/signup.php". Pages directory does not exist, and I don't know if I should reimplement that part or I missed them from some other project? I guess that there are also more pages files missing for when the user is logged ...and so on.

Thank you very much.

**Comment by ocram** [comment]
@xavimc Thanks! The paths that you’re referring to don’t have to physically exist as files. Rather, their existence is simulated by the `RewriteRule` directives in the `.htaccess` file from the root directory. So you need to enable support for `.htaccess` URL rewriting.

**Comment by xavimc** [comment]
Hi again ocram,
It worked! Thank you for pointing me in the right direction.

For anyone in the same situation, here are the problems I found and the steps I followed to solve:

Installed Ubuntu 18.04 in a virtual machine and configured the environment following this tutorial:
(https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-ubuntu-18-04)

Follow project instructions section:
Create a new MySQL or MariaDB database
Import the tables from database/structure.sql into the database
Rename config.example.php to config.php and fill in proper values

Some troubleshoot that also helped, enable .htaccess override that was ignored by apache (https://docs.bolt.cm/3.4/howto/making-sure-htaccess-works)
sudo gedit /etc/apache2/apache2.conf
Change allow override from None to All
<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>

Enable apache2 mod_rewrite (https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-16-04)
sudo a2enmod rewrite
sudo systemctl restart apache2

Enable apache2 mod "Headers" (https://www.garron.me/es/cortos/invalid-command-header-htaccess-apache.html)
sudo cd /etc/apache2/mods-enabled/
sudo ln -s ../mods-available/headers.load headers.load
sudo service apache2 restart

Give permission to apache to write in temp and uploads directories to allow saving strings xml (https://stackoverflow.com/questions/8103860/move-uploaded-file-gives-failed-to-open-stream-permission-denied-error-after)
cd to your web root directory
sudo chown -R www-data temp
sudo chown -R www-data uploads

Install php-xml module (https://stackoverflow.com/questions/31206186/call-to-undefined-function-simplexml-load-string)
sudo apt install php-xml

That's all!

**Comment by ocram** [comment]
Yes, that looks good. Thank you!
